      # Warning: indentation here matters!

      # Pytorch iOS builds
      - pytorch_ios_build:
          requires:
            - setup
          filters:
            branches:
              only: master
  
