name: Lint

on:
  pull_request

jobs:
  flake8_py3:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.4
          architecture: x64
      - name: Checkout PyTorch
        uses: actions/checkout@master
      - name: Run flake8
        run: |
          set -eux
          pip install flake8
          flake8 --exit-zero > ${GITHUB_WORKSPACE}/flake8_output.txt
      - name: Add annotations
        uses: suo/add-annotations-github-action@master
        with:
          checkName: 'flake8_py3'
          fileLocation: 'flake8_output.txt'
          regex: '^(?<filename>.*?):(?<lineNumber>\d+):(?<columnNumber>\d+): (?<errorCode>\w\d+) (?<errorDesc>[\s|\w]*)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
